name: Android CI

on:
  push:
    branches: [ "main", "setup-github-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit Tests & Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Lint
      run: ./gradlew lintDebug

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/build/reports/tests/
          **/build/reports/lint-results-debug.xml

  instrumentation-tests:
    name: Run Instrumentation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # Note: This can be slow and use more GitHub Actions minutes

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
